ALTER TABLE posts
ADD COLUMN privacy varchar(3) DEFAULT 'PR1' NOT NULL,
ADD COLUMN deleted boolean NOT NULL DEFAULT FALSE,
ADD COLUMN reported boolean NOT NULL DEFAULT FALSE,
ADD COLUMN created TIMESTAMPTZ DEFAULT Now()

