ALTER TABLE posts
ADD COLUMN privacy varchar(3) DEFAULT 'PRI' NOT NULL,
ADD COLUMN deleted boolean NOT NULL DEFAULT FALSE,
ADD COLUMN reported boolean NOT NULL DEFAULT FALSE,
ADD COLUMN created_at TIMESTAMPTZ DEFAULT Now() 